import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
import dotenv from 'dotenv';
dotenv.config({ path: path.join(__dirname, '.env') });

// Generate config.js for client-side use
const config = {
  MINIO_ENDPOINT: process.env.MINIO_ENDPOINT || 'localhost',
  MINIO_PORT: parseInt(process.env.MINIO_PORT || '9000'),
  MINIO_USE_SSL: process.env.MINIO_USE_SSL === 'true',
  SERVER_PORT: parseInt(process.env.SERVER_PORT || '3001'),
  CURRENTS_BUCKET_NAME: process.env.CURRENTS_BUCKET_NAME || 'braze-currents',
  CURRENTS_REGION: process.env.CURRENTS_REGION || 'us-east-1'
};

const configContent = `// Auto-generated from .env file
// Do not edit this file directly - edit .env and run: npm run load-env

export const MINIO_ENDPOINT = "${config.MINIO_ENDPOINT}";
export const MINIO_PORT = ${config.MINIO_PORT};
export const MINIO_USE_SSL = ${config.MINIO_USE_SSL};
export const SERVER_PORT = ${config.SERVER_PORT};
export const CURRENTS_BUCKET_NAME = "${config.CURRENTS_BUCKET_NAME}";
export const CURRENTS_REGION = "${config.CURRENTS_REGION}";
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), configContent);

console.log('✓ Generated config.js from .env file');
console.log(`  MinIO Endpoint: ${config.MINIO_ENDPOINT}:${config.MINIO_PORT}`);
console.log(`  Bucket: ${config.CURRENTS_BUCKET_NAME}`);
console.log(`  Server Port: ${config.SERVER_PORT}`);
