#!/usr/bin/env node

/**
 * Load environment variables from .env file and generate config.js
 * This script reads .env and creates a config.js file for the client-side app
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envPath = path.join(__dirname, '.env');
const configPath = path.join(__dirname, 'public', 'config.js');

// Read .env file
function loadEnvFile() {
    if (!fs.existsSync(envPath)) {
        console.warn(`Warning: .env file not found at ${envPath}`);
        console.warn('Please create a .env file based on .env.example');
        return {};
    }

    const envContent = fs.readFileSync(envPath, 'utf-8');
    const envVars = {};

    envContent.split('\n').forEach(line => {
        // Skip comments and empty lines
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) {
            return;
        }

        // Parse KEY=VALUE format
        const match = trimmed.match(/^([^=]+)=(.*)$/);
        if (match) {
            const key = match[1].trim();
            const value = match[2].trim().replace(/^["']|["']$/g, ''); // Remove quotes
            envVars[key] = value;
        }
    });

    return envVars;
}

// Generate config.js from environment variables
function generateConfig(envVars) {
    const apiKey = envVars.BRAZE_REST_API_KEY || '';
    const endpoint = envVars.BRAZE_REST_ENDPOINT || 'https://rest.iad-03.braze.com';

    const configContent = `// Braze REST API Configuration
// This file is auto-generated from .env by load-env.js
// Do not edit this file manually - edit .env instead and run: npm run load-env

export const BRAZE_REST_API_KEY = '${apiKey.replace(/'/g, "\\'")}';
export const BRAZE_REST_ENDPOINT = '${endpoint.replace(/'/g, "\\'")}';
`;

    // Ensure public directory exists
    const publicDir = path.dirname(configPath);
    if (!fs.existsSync(publicDir)) {
        fs.mkdirSync(publicDir, { recursive: true });
    }

    fs.writeFileSync(configPath, configContent, 'utf-8');
    console.log('✓ Generated config.js from .env file');
    console.log(`  API Key: ${apiKey ? apiKey.substring(0, 10) + '...' : '(not set)'}`);
    console.log(`  Endpoint: ${endpoint}`);
}

// Main execution
try {
    const envVars = loadEnvFile();
    generateConfig(envVars);
} catch (error) {
    console.error('Error loading environment variables:', error);
    process.exit(1);
}
